# This file was generated by GoReleaser. DO NOT EDIT.
cask "m8" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "7f3a06d35d3f20f29f6997115ba07a1d35436b32b70cc9d9e94f20e0f1783918"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eaa08b22030e13cdc09cf9124e13ba4cd0487b2e45c248021bc058da64961909"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf617d06aacb1045d83a8be0bd7def826429ef19850c2e8810a02b5c18c5fba5"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d80043acf135fa8169875ae66681387ca7f359f8b449f3d8a7b9e410b287574"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_linux_amd64.tar.gz"
    end
  end

  name "m8"
  desc "PostgreSQL migration tool"
  homepage "https://github.com/ags-slc/m8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m8"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/m8"]
    end
  end

  # No zap stanza required
end
