# This file was generated by GoReleaser. DO NOT EDIT.
cask "m8" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "40376d071c061be8c91f5af8c6bb4b381ec4aef1242729c053af4871b568387b"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ceb9084c0f0ad30a08a3d094b2302f9387f4c6512e670271b04de0f2e83ad7cd"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "696ac1e8f9a32870d8547c0a91d21ac27f8358aca2a5df00c2b3ae165e3fea80"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c4238e3e4d31287d85fc9265f0c88346592c38872dfbf239b96cee8187971557"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_linux_amd64.tar.gz"
    end
  end

  name "m8"
  desc "PostgreSQL migration tool"
  homepage "https://github.com/ags-slc/m8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m8"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/m8"]
    end
  end

  # No zap stanza required
end
