# This file was generated by GoReleaser. DO NOT EDIT.
cask "m8" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "7fbf37c7a21b706b0f166cd018af52608b7f46801ec665993dab66a2f273f099"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "464951c26c7d66a1e122b530327d9cda2a5c7ec9d23c184d2ec81d332fb8a667"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "52e8163702decf908c2ad1f92ed063d6a1107d668182e52b6252d7722edaa09a"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bbf6d17792975e5b20675491695c4157ce88dc5e5d33fa406be0d3148c983310"
      url "https://github.com/ags-slc/m8/releases/download/v#{version}/m8_#{version}_linux_amd64.tar.gz"
    end
  end

  name "m8"
  desc "PostgreSQL migration tool"
  homepage "https://github.com/ags-slc/m8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m8"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/m8"]
    end
  end

  # No zap stanza required
end
